lab4/bazy4/bazy4/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
]

lab4/bazy4/home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add-faculty/$', views.new_faculty, name='new faculty'),
    url(r'^view-faculties/$', views.show_faculties, name='Faculty list'),
    url(r'^add-student/$', views.add_student, name='new student'),
    url(r'^view-students/$', views.show_students, name='Student list'),
    url(r'^edit-student/$', views.edit_student, name='new student'),
    url(r'^delete-student/$', views.delete_student, name='delete student'),
    url(r'^search-students/$', views.search_student, name='search student'),

]

lab4/bazy4/home/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Faculty(models.Model):
    idfaculty = models.AutoField(primary_key=True)
    facultyname = models.CharField('faculty name', db_column='facultyName', unique=True, max_length=60)  # Field name made lowercase.
    faculty = models.Manager()

    def __str__(self):
        return self.facultyname

    class Meta:
        db_table = 'faculty'
        verbose_name_plural = 'faculties'


class Staff(models.Model):
    idstaff = models.AutoField(primary_key=True)
    firstname = models.CharField(max_length=80)
    lastname = models.CharField(max_length=90)
    email = models.CharField(unique=True, max_length=60)
    password = models.CharField(max_length=64)
    faculty_idfaculty = models.ForeignKey(Faculty, models.DO_NOTHING, db_column='faculty_idfaculty')

    def __str__(self):
        return self.firstname + ' ' + self.lastname

    class Meta:
        db_table = 'staff'


class Student(models.Model):
    idstudent = models.AutoField(primary_key=True)
    fristname = models.CharField(max_length=80)
    lastname = models.CharField(max_length=100)
    email = models.CharField(max_length=60)
    password = models.CharField(max_length=64)
    addressline = models.CharField(db_column='addressLine', max_length=100)  # Field name made lowercase.
    city = models.CharField(max_length=45)
    zipcode = models.CharField(db_column='zipCode', max_length=5)  # Field name made lowercase.
    faculty_idfaculty = models.ForeignKey(Faculty, models.DO_NOTHING, db_column='faculty_idfaculty')

    student = models.Manager()

    def __str__(self):
        return self.fristname + ' ' + self.lastname

    class Meta:
        db_table = 'student'

lab4/bazy4/home/forms.py
from django import forms
from home.models import *


class StudentForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Student
        fields = '__all__'


class StaffForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Staff
        fields = '__all__'


class AddFacultyForm(forms.ModelForm):
    facultyname = forms.CharField(label='Faculty name', max_length=60)

    class Meta:
        model = Faculty
        fields = '__all__'


class AddStudentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.edit = kwargs.pop('edit', None)
        self.id = kwargs.pop('id', None)
        super(AddStudentForm, self).__init__(*args, **kwargs)
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Student
        fields = '__all__'

    def clean(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password1 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        if self.edit is False:
            if Student.student.filter(email=self.cleaned_data.get('email')).exists():
                raise forms.ValidationError(
                    "User with that email already exists!")
        else:
            email = Student.student.get(
                pk=self.id).email
            if Student.student.filter(email=self.cleaned_data.get('email')).exists():
                if self.cleaned_data.get('email').strip() != email.strip():
                    raise forms.ValidationError(
                        "User with that email already exists!")

        return self.cleaned_data

lab4/bazy4/home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import *


def new_faculty(request):
    faculty = ''
    if request.method == 'POST':
        form = AddFacultyForm(request.POST)
        faculty = request.POST.get('facultyname')
        if form.is_valid():
            faculty = form.cleaned_data['facultyname']
            form.save()
            return render(request, 'add-faculty-success.html', {'name': faculty})
    else:
        form = AddFacultyForm()

    return render(request, 'add-faculty.html', {'form': form, 'faculty': faculty})


def show_faculties(request):
    from .models import Faculty
    param = request.GET.get('sort')
    if request.GET.get('sort') == 'asc':
        faculties = Faculty.faculty.order_by('facultyname')
    elif request.GET.get('sort') == 'desc':
        faculties = Faculty.faculty.order_by('-facultyname')
    else:
        faculties = Faculty.faculty.order_by('facultyname')

    return render(request, 'view-faculties.html', {'faculties': faculties, 'sort': param})


def add_student(request):
    faculties = Faculty.faculty.order_by('facultyname')
    if request.method == 'POST':
        form = AddStudentForm(request.POST, edit=False)
        if form.is_valid():
            name = form.cleaned_data.get(
                'fristname') + ' ' + form.cleaned_data.get('lastname')
            form.save()
            student = Student.student.get(email=form.cleaned_data.get('email'))
            return render(request, 'add-student-success.html', {'name': name, 'id': student.pk})
        else:
            requestDict = request.POST.dict()
            print()
            return render(request, 'add-student.html', {'form': form, 'options': faculties, 'data': requestDict, 'id' : requestDict.get('faculty_idfaculty'), 'edit' : False})
    else:
        form = AddStudentForm()

    return render(request, 'add-student.html', {'form': form, 'options': faculties})


def show_students(request):
    from .models import Faculty, Student
    sortFirstName = request.GET.get('sortFirstName')
    sortLastName = request.GET.get('sortLastName')
    sortEmail = request.GET.get('sortEmail')
    sortFaculty = request.GET.get('sortFaculty')

    if sortFirstName == 'asc':
        students = Student.student.order_by('fristname')
    elif sortFirstName == 'desc':
        students = Student.student.order_by('-fristname')
    elif sortLastName == 'asc':
        students = Student.student.order_by('lastname')
    elif sortLastName == 'desc':
        students = Student.student.order_by('-lastname')
    elif sortEmail == 'asc':
        students = Student.student.order_by('email')
    elif sortEmail == 'desc':
        students = Student.student.order_by('-email')
    elif sortFaculty == 'asc':
        students = Student.student.order_by('faculty_idfaculty')
    elif sortFaculty == 'desc':
        students = Student.student.order_by('-faculty_idfaculty')
    else:
        students = Student.student.order_by('fristname')
    facultyID = request.GET.get('from_faculty')
    if facultyID is not None:
        try:
            if Student.student.filter(faculty_idfaculty=facultyID).count() == 0:
                return render(request, 'view-students-faculty.html', {'result' : False})
            students = Student.student.filter(faculty_idfaculty=facultyID)
        except Exception:
            return render(request, 'view-students-faculty.html', {'result' : False})
        return render(request, 'view-students-faculty.html', {'result' : True, 'students' : students})
    id = request.GET.get('id')
    if id is not None:
        try:
            student = Student.student.get(pk=id)
        except Exception:
            return render(request, 'error.html', {'error': 'Student not found!'})
        return render(request, 'show-student-info.html', {'student': student})

    return render(request, 'view-students.html', {'students': students, 'sortFirstName': sortFirstName,
                                                  'sortLastName': sortLastName, 'sortEmail': sortEmail, 'sortFaculty': sortFaculty})


def edit_student(request):
    from django.forms.models import model_to_dict
    id = request.GET.get('id')
    if id is not None:
        try:
            student = Student.student.get(pk=id)
        except Exception:
            return render(request, 'error.html', {'error': 'Student not found!'})
    else:
        return render(request, 'error.html', {'error': 'Wrong argument!'})
    faculties = Faculty.faculty.order_by('facultyname')
    if request.method == 'POST':
        form = AddStudentForm(request.POST, edit=True, id=id, instance=student)
        if form.is_valid():
            form.save()
            return render(request, 'edit-student-success.html', {'name': student.fristname + ' ' + student.lastname,
                                                                 'id': student.pk})
    else:
        form = AddStudentForm()
    return render(request, 'add-student.html', {'form': form, 'data':  model_to_dict(student), 'options': faculties,
                                                'id': student.pk, 'edit': True})

def delete_student(request):
    if request.method == 'POST':
        studentid = request.POST.get('id')
        try:
            student = Student.student.get(pk=studentid)
        except Exception:
            return render(request, 'error.html', {'error': 'Student not found!'})
        try:
            student.delete()
        except Exception:
            return render(request, 'error.html', {'error': 'This student cannot be deleted ;)'})
        return render(request, 'delete-student.html')
    return render(request, 'error.html', {'error': 'Wrong form action!'})

def search_student(request):
    firstname = request.GET.get('searchFirstName')
    lastname = request.GET.get('searchLastName')
    if len(request.GET) < 3:
           return render(request, 'search-students.html')
    if firstname is '' and lastname is '':
        return render(request, 'search-students.html')
    elif firstname is '':
        try:
            student = Student.student.filter(lastname__icontains=lastname)
            if Student.student.filter(lastname__icontains=lastname).count() == 0:
                raise 'No students!'
        except Exception:
            student = None
    elif lastname is '':
        try:
            student = Student.student.filter(fristname__icontains=firstname)
            if Student.student.filter(fristname__icontains=firstname).count() == 0:
                raise 'No students!'
        except Exception:
            student = None
    else:
        try:
            student = Student.student.filter(fristname__icontains=firstname, lastname__icontains=lastname)
            if Student.student.filter(fristname__icontains=firstname, lastname__icontains=lastname).count() == 0:
                raise 'No students!'
        except Exception:
            student = None
    if student is not None:
        return render(request, 'search-students.html', {'students' : student, 'result' : True})
    else:
        print('Err')
        return render(request, 'search-students.html', {'result' : False})

def index(request):
    return render(request, 'main.html')


def contact(request):
    return render(request, 'contact.html')


def about(request):
    return render(request, 'about.html')

lab4/bazy4/home/templates/about.html
{% extends "body.html" %} {% block content %}
<h1>O projekcie</h1>
<p>
    Projekt powstał na potrzeby edukacyjne i ma charakter czysto poglądowy. Autor serwisu nigdy nie programował w Django - jest to jego pierwsza aplikacja webowa napisana w tym framework'u.
    Wszelkie pytania co do projektu nalezy nadsyłać na adres mailowy podany w zakładce <a href="/contact">kontakt</a>
</p>

{% endblock %}

lab4/bazy4/home/templates/add-faculty-success.html
{% extends "body.html" %} {% block content %} {% load static %}
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <h1>Operation successful!</h1>
        <div class="alert alert-success alert-dismissable" role="alert">
				<p>Great! {{name}} faculty has been added!</p>
		</div>
        <div class="btn-group">
                    <a href="/add-faculty/" class="btn btn-primary " name="next-faculty" type="submit">
        Add next faculty
       </a>
                  <a href="/" class="btn btn-default " name="home"><span class="glyphicon glyphicon-home"></span>
        Go to homepage
       </a>
                </div>
    </div>
</div>
{% endblock %}

lab4/bazy4/home/templates/add-faculty.html
{% extends "body.html" %} {% block content %} {% load static %}
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
        <form action="/add-faculty/" method="post">
            {% csrf_token %}
            <div class="form-group ">
                <label class="control-label " for="facultyname">
       Faculty name
      </label>
      <input class="form-control" id="facultyname" name="facultyname" value="{{faculty}}" type="text" required />
                <span class="help-block" id="hint_name">
       Enter the name of faculty
      </span>
            </div>
            <div class="form-group">
                <div class="btn-group">
                    <button class="btn btn-primary " name="submit" type="submit"><span class="glyphicon glyphicon-ok"></span>
        Submit
       </button>
        <a href="/" class="btn btn-default" name="home"><span class="glyphicon glyphicon-home"></span>
        Go to homepage
       </a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

lab4/bazy4/home/templates/add-student-success.html
{% extends "body.html" %} {% block content %} {% load static %}
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <h1>Operation successful!</h1>
        <div class="alert alert-success alert-dismissable" role="alert">
				<p>Great! <a href=/view-students/?id={{id}}>{{name}}</a> has been added to student of our university! ;)</p>
		</div>
        <div class="btn-group">
                    <a href="/add-student/" class="btn btn-primary " name="next-student" type="submit">
        Add next student
       </a>
                  <a href="/" class="btn btn-default " name="home"><span class="glyphicon glyphicon-home"></span>
        Go to homepage
       </a>
                </div>
    </div>
</div>
{% endblock %}

lab4/bazy4/home/templates/add-student.html
{% extends "body.html" %} {% block content %} {% load static %}
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        {% if edit %}
        <h1>Edit Student</h1>
        {% else %}
        <h1> Add student</h1>
        {% endif %}
        {% if form.errors %} {% for field in form %} {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %} {% endfor %} {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %} {% endif %}
        {% if edit %}
        <form action="/edit-student/?id={{id}}" method="post">
        {% else %}
        <form action="/add-student/" method="post">
        {% endif %}
        {% csrf_token %}
        {% load get_data %}
            <div class="form-group ">
                <label class="control-label requiredField" for="firstname">
       First name
       <span class="asteriskField">
        *
       </span>
      </label>
                <input class="form-control" id="fristname" name="fristname" type="text" value="{% get_data 'fristname' data %}" />
            </div>
            <div class="form-group ">
                <label class="control-label requiredField" for="lastname">
       Last name
       <span class="asteriskField">
        *
       </span>
      </label>
                <input class="form-control" id="lastname" name="lastname" type="text" value="{% get_data 'lastname' data %}" />
            </div>
            <div class="form-group ">
                <label class="control-label requiredField" for="email">
       Email
       <span class="asteriskField">
        *
       </span>
      </label>
                <input class="form-control" id="email" name="email" type="text" value="{% get_data 'email' data %}" />
            </div>
            <div class="form-group ">
                <label class="control-label requiredField" for="password">
       Password
       <span class="asteriskField">
        *
       </span>
      </label>
                <input class="form-control" id="password" name="password" type="password" />
            </div>
            <div class="form-group ">
                <label class="control-label requiredField" for="password2">
       Retype password
       <span class="asteriskField">
        *
       </span>
      </label>
                <input class="form-control" id="password2" name="password2" type="password" />
            </div>
            <div class="form-group ">
                <label class="control-label requiredField" for="addressline">
       Address
       <span class="asteriskField">
        *
       </span>
      </label>
                <input class="form-control" id="addressline" name="addressline" type="text" value="{% get_data 'addressline' data %}" />
            </div>
            <div class="form-group ">
                <label class="control-label requiredField" for="city">
       City
       <span class="asteriskField">
        *
       </span>
      </label>
                <input class="form-control" id="city" name="city" type="text" value="{% get_data 'city' data %}" />
            </div>
            <div class="form-group ">
                <label class="control-label requiredField" for="zipcode">
       Zip code (in XXYYY format)
       <span class="asteriskField">
        *
       </span>
      </label>
                <input class="form-control" id="zipcode" name="zipcode" type="text" value="{% get_data 'zipcode' data %}"/>
            </div>
            <div class="form-group ">
                <label class="control-label requiredField" for="faculty_idfaculty">
       Faculty name
       <span class="asteriskField">
        *
       </span>
      </label>
                <select class="select form-control" id="id_faculty_idfaculty" name="faculty_idfaculty">
        {% if edit %}
        {% get_data 'faculty_idfaculty' data as selectedid %}    
        {% for faculty in options %}
        {% if faculty.pk == selectedid %}
       
       <option value="{{faculty.pk}}" selected>
        {{faculty}}
       </option>
       {% else %}
        <option value="{{faculty.pk}}">
        {{faculty}}
       </option>
       {% endif %}
       {% endfor %}
       {% else %}
       {% for faculty in options %}
        {% if faculty.pk|slugify == id|slugify %}
        {{id}}
       <option value="{{faculty.pk}}" selected>
        {{faculty}}
       </option>
       {% else %}
        <option value="{{faculty.pk}}">
        {{faculty}}
       </option>
        {% endif %}
       {% endfor %}
       {% endif %}
      </select>
            </div>
            <div class="form-group">
                <div class="btn-group">
                    <button class="btn btn-primary " name="submit" type="submit"><span class="glyphicon glyphicon-ok"></span>
        Submit
       </button>
                    <a href="/" class="btn btn-default" name="home"><span class="glyphicon glyphicon-home"></span>
        Go to homepage
       </a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

lab4/bazy4/home/templates/body.html
{% include "head.html" %}
<body>
    {% include "navbar.html" %}
    <div class="page-header">
        <div class="container" style="padding-bottom: 60px;">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% include "footer.html" %}

lab4/bazy4/home/templates/contact.html
{% extends "body.html" %} {% block content %} {% load static %}
<div class="row">
    <div class="col-xs-4 col-sm-2 col-md-4">
        <img class="img-responsive" src="{% static 'img/me.jpeg' %}" alt="me">
    </div>
    <div class="col-xs-8 col-sm-10 col-md-8">
        <h1> O mnie</h1>
        <p> Adrian Kastrau <br> Politechnika Gdańska <br> Wydział Fizyki Technicznej i Matematyki Stosowanej<br> Informatyka
            Stosowana
            <br> E-mail: adrkastr[na]student[kropka]pg[kolejna kropa]gda[ostatnia kropka]pl
        </p>
    </div>
</div>
{% endblock %}

lab4/bazy4/home/templates/delete-student.html
{% extends "body.html" %} {% block content %} {% load static %}
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <h1>Operation successful!</h1>
        <div class="alert alert-success alert-dismissable" role="alert">
				<p>Great! Student has been removed! ;)</p>
		</div>
        <div class="btn-group">
                    <a href="/view-students/" class="btn btn-primary " name="student" type="submit"><span class="glyphicon glyphicon-education"></span>
        Student list
       </a>
                  <a href="/" class="btn btn-default " name="home"><span class="glyphicon glyphicon-home"></span>
        Go to homepage
       </a>
                </div>
    </div>
</div>
{% endblock %}

lab4/bazy4/home/templates/error.html
{% extends "body.html" %} {% block content %} {% load static %}
<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <h1>Error occurred!</h1>
        <div class="alert alert-danger alert-dismissable" role="alert">
				<p>{{error}}</p>
		</div>
        <div class="btn-group">
                  <a href="/" class="btn btn-default " name="home"><span class="glyphicon glyphicon-home"></span>
        Go to homepage
       </a>
                </div>
    </div>
</div>
{% endblock %}

lab4/bazy4/home/templates/head.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bazy - projekt</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}" >
</head>

lab4/bazy4/home/templates/navbar.html
{% load static %}
<!-- navbar -->
<div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
                aria-controls="navbar">
            <span class="sr-only">Menu</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/python-logo.png' %}" alt="logo-python" style="max-width:100px; margin-top: -7px; display: inline-block;"
                />
                <span style="display: inline-block;">Projekt Django</span>
            </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
                <li {% if request.path == '/' %}class="active"{% endif %}><a href="/">Strona głowna</a></li>
                 <li><a href="/view-faculties"><span class="glyphicon glyphicon-list">&ensp;</span>Show all faculties</a></li>
                 <li><a href="/view-students"><span class="glyphicon glyphicon-education">&ensp;</span>Student list</a></li>
                <li><a href="/search-students"><span class="glyphicon glyphicon-search">&ensp;</span>Search - students</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/add-faculty"><span class="glyphicon glyphicon-plus">&ensp;</span>Add faculty</a></li>
                        <li><a href="/view-faculties"><span class="glyphicon glyphicon-list">&ensp;</span>Show all faculties</a></li>
                        <li><a href="/add-student"><span class="glyphicon glyphicon-user">&ensp;</span>Add student</a></li>
                        <li><a href="/view-students"><span class="glyphicon glyphicon-education">&ensp;</span>Student list</a></li>
                        <li><a href="/search-students"><span class="glyphicon glyphicon-search">&ensp;</span>Search - students</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

lab4/bazy4/home/templates/view-faculties.html
{% extends "body.html" %} {% block content %} {% load static %}
<h1> Faculties</h1>
<table class="table table-hover">
    <thead>
      <tr>
          {% if sort == 'asc' %}
        <th><a href="/view-faculties/?sort=desc">Faculty name<span class="glyphicon glyphicon-menu-up"></span></a></th>
          {% elif sort == 'desc' %}
          <th><a href="/view-faculties/?sort=asc">Faculty name<span class="glyphicon glyphicon-menu-down"></span></a></th>
          {% else %}
           <th><a href="/view-faculties/?sort=desc">Faculty name<span class="glyphicon glyphicon-menu-up"></span></a></th>
           {% endif %}
      </tr>
    </thead>
    <tbody>
     {% for faculty in faculties %}
     <tr>
         <td><a href="/view-students/?from_faculty={{faculty.pk}}">{{faculty}}</a></td>
     </tr>
     {% endfor %}
    </tbody>
  </table>
{% endblock %}

lab4/bazy4/home/templates/view-students-faculty.html
 {% extends "body.html" %} {% block content %} {% load static %}
 {% if result %}
        <h1> List of students</h1>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th><a>Info</a></th>
                    <th><a>First name</a></th>
                    <th><a>Last name</a></th>
                    <th><a>Faculty</a></th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td><a href="/view-students?id={{student.pk}}"><span class="glyphicon glyphicon-eye-open">&ensp;</span></a></td>
                    <td>{{student.fristname}}</td>
                    <td>{{student.lastname}}</td>
                    <td>{{student.faculty_idfaculty}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% elif result == False %}
        <h1>No results!</h1>
        {% endif %}
{% endblock %}

lab4/bazy4/home/templates/view-students.html
{% extends "body.html" %} {% block content %} {% load static %}
<h1> List of students</h1>
<table class="table table-hover">
    <thead>
      <tr>
          <th><a>Info</a></th>
          {% if sortFirstName == 'asc' %}
        <th><a href="/view-students/?sortFirstName=desc">First name<span class="glyphicon glyphicon-menu-up"></span></a></th>
          {% elif sortFirstName == 'desc' %}
          <th><a href="/view-students/?sortFirstName=asc">First name<span class="glyphicon glyphicon-menu-down"></span></a></th>
          {% else %}
           <th><a href="/view-students/?sortFirstName=desc">First name<span class="glyphicon glyphicon-menu-up"></span></a></th>
           {% endif %}
        {% if sortLastName == 'asc' %}
        <th><a href="/view-students/?sortLastName=desc">Last name<span class="glyphicon glyphicon-menu-up"></span></a></th>
          {% elif sortLastName == 'desc' %}
          <th><a href="/view-students/?sortLastName=asc">Last name<span class="glyphicon glyphicon-menu-down"></span></a></th>
          {% else %}
           <th><a href="/view-students/?sortLastName=desc">Last name<span class="glyphicon glyphicon-menu-up"></span></a></th>
           {% endif %}
        {% if sortEmail == 'asc' %}
        <th><a href="/view-students/?sortEmail=desc">Email address<span class="glyphicon glyphicon-menu-up"></span></a></th>
          {% elif sortEmail == 'desc' %}
          <th><a href="/view-students/?sortEmail=asc">Email address<span class="glyphicon glyphicon-menu-down"></span></a></th>
          {% else %}
           <th><a href="/view-students/?sortEmail=desc">Email address<span class="glyphicon glyphicon-menu-up"></span></a></th>
           {% endif %}
        {% if sortFaculty == 'asc' %}
        <th><a href="/view-students/?sortFaculty=desc">Faculty<span class="glyphicon glyphicon-menu-up"></span></a></th>
          {% elif sortFaculty == 'desc' %}
          <th><a href="/view-students/?sortFaculty=asc">Faculty<span class="glyphicon glyphicon-menu-down"></span></a></th>
          {% else %}
           <th><a href="/view-students/?sortFaculty=desc">Faculty<span class="glyphicon glyphicon-menu-up"></span></a></th>
           {% endif %}
      </tr>
    </thead>
    <tbody>
     {% for student in students %}
     <tr>
         <td><a href="/view-students?id={{student.pk}}"><span class="glyphicon glyphicon-eye-open">&ensp;</span></a></td>
         <td>{{student.fristname}}</td>
         <td>{{student.lastname}}</td>
         <td>{{student.email}}</td>
         <td>{{student.faculty_idfaculty}}</td>
     </tr>
     {% endfor %}
    </tbody>
  </table>
{% endblock %}